# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-21 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=1000)),
                ('lineOne', models.CharField(blank=True, max_length=1000)),
                ('lineTwo', models.CharField(blank=True, max_length=1000)),
                ('city', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(blank=True, max_length=1000)),
                ('country', models.CharField(blank=True, max_length=1000)),
                ('zip', models.CharField(blank=True, max_length=1000)),
                ('phoneNumber', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('filename', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=1000)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('subtotal', models.CharField(blank=True, max_length=1000)),
                ('shippingPrice', models.CharField(blank=True, max_length=1000)),
                ('tax', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=1000)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
                ('brandId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('filename', models.CharField(blank=True, max_length=1000)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategoryId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Subcategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
