# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180621_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('long', models.DecimalField(decimal_places=4, max_digits=8)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
