# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180701_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.City'),
            preserve_default=False,
        ),
    ]
