# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
